### ISSUE TITLE
Bug report: Time setting

### ISSUE THREAD

**Issue by dashamstyr** [daisieh/lmc_carshare#3]
I selected November 11 as the date (one week in the future) but the available hours seemed to be limited to 20h and later.

**Comment by daisieh** [comment]
Did you try scrolling up on the hours thingy?

**Comment by dashamstyr** [comment]
yes.  the earliest hour available was 20.  However, if this can't be replicated maybe it was a transient thing.  Closed for now, I will keep an eye out for it in future use tests.
