### ISSUE TITLE
Feature request: Edit search after no results

### ISSUE THREAD

**Issue by dashamstyr** [daisieh/lmc_carshare#4]
Currently if my search returns no available cars, The only option is to reset the search and star again.  Request instead to go back to the search and edit it to perhaps get a better result. (say. by reducing tags or expanding hours)

**Comment by daisieh** [comment]
This might be worth looking at in the future, but it is scary and leads to horrible bugs, so I didn't want to do it right now.

**Comment by dashamstyr** [comment]
enhancement tag accepted

**Comment by daisieh** [comment]
Christine has mentioned this too: it will be much more complicated to allow date/time tweaking, but it should be pretty easy to add the ability to filter on more/less features.

**Comment by daisieh** [comment]
Okay, as of https://github.com/daisieh/lmc_carshare/commit/b88fd675fd25bf3f6312f11765c74879a130c16f, you can pick and filter on tags after you've performed the search.
