### ISSUE TITLE
time setting

### ISSUE THREAD

**Issue by dashamstyr** [daisieh/lmc_carshare#7]
Steps:

 1) Set start date to 11/12/2020 @ 9:00
 (end date automatically set to 11/12/2020 @10:00)

2) Set end date to 11/12/2020 @ 12:00
(start date reset to 11/09/2020 @18:00)

**Comment by daisieh** [comment]
I tweaked the time setting, so #2 shouldn't happen anymore. The first one is expected behavior: I wanted to make it difficult to accidentally set an end time that is before the start time. An hour seemed to me to be a reasonable default.
